check on pr title in success when it is skipped

diff --git a/.github/workflows/pr-title.yml b/.github/workflows/pr-title.yml
--- a/.github/workflows/pr-title.yml
+++ b/.github/workflows/pr-title.yml
@@ -24,7 +24,8 @@ jobs:
       !startsWith(github.head_ref, 'dependabot') &&
       !startsWith(github.head_ref, 'release/') &&
       !startsWith(github.head_ref, 'hotfix/') &&
-      !startsWith(github.head_ref, 'main')
+      !startsWith(github.head_ref, 'main') &&
+      !startsWith(github.head_ref, 'chore/')
     steps:
       - name: Checkout
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -62,3 +63,25 @@ jobs:
           # Configure which scopes are allowed (newline-delimited).
           scopes: |
             (?:\w+)-\d+
+  check-rsult:
+    runs-on: ubuntu-22.04
+    needs: validate-pr-title
+    steps:
+      - name: Check Status
+        run: |
+          # Get the result from the previous job
+          RESULT="${{ needs.validate-pr-title.result }}"
+
+          echo "The previous job is finished with status: $RESULT"
+           
+          # - If the result is 'success', everything is ok.
+          # - If the result is 'skipped', everything is ok (because we skipped the previous job intentionally).
+          # - If the result is 'failure' or 'cancelled', we have to fail.
+
+          if [[ "$RESULT" == "failure" || "$RESULT" == "cancelled" ]]; then
+            echo "The validation is failed"
+            exit 1
+          else
+            echo "Check in success (or skipped intentionally)."
+            exit 0
+          fi
